# do not use this dockerfile for deployments. This is just for development and trying things out.
# Go to https://lukas-heiligenbrunner.github.io/AURCache/docs/overview/introduction for examples.
version: '3'
services:
  aurcache:
    build:
        context: .
        dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - LOG_LEVEL=debug
      #- BUILD_ARTIFACT_DIR=artifact_cache # also absolute path is possible
      - BUILD_ARTIFACT_DIR=/home/lukas/IdeaProjects/AURCache/tmp_cache # also absolute path is possible
    volumes:
      - ./aurcache/db:/app/db
      - ./aurcache/repo:/app/repo
      - /run/user/1000/podman/podman.sock:/var/run/docker.sock
      - /home/lukas/IdeaProjects/AURCache/tmp_cache:/app/builds
    privileged: true

volumes:
  artifact_cache:
    name: artifact_cache
    driver: local