# do not use this dockerfile for deployments. This is just for development and trying things out.
# Go to https://lukas-heiligenbrunner.github.io/AURCache/docs/overview/introduction for examples.
version: '3'
services:
  aurcache:
    build:
        context: .
        dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - LOG_LEVEL=debug
    volumes:
      - ./aurcache/db:/app/db
      - ./aurcache/repo:/app/repo
    privileged: true