services:
  aurcache:
    build:
        context: .
        dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - LOG_LEVEL=debug
    volumes:
      - ./aurcache/db:/app/db
      - ./aurcache/repo:/app/repo
    privileged: true