[workspace]
resolver = "2"
members = [
    "pacman-mirrors",
    "pacman-repo-utils",
    "aurcache",
    "aurcache-builder",
    "aurcache-deps",
    "aurcache-db",
    "aurcache-api",
    "aurcache-activitylog",
    "aurcache-utils",
    "aurcache-scheduler",
    "aurcache-types"]

[workspace.dependencies]
tokio = "1.53.1"
anyhow = "1.0.104"
reqwest = "0.13.4"
tracing = "0.1.44"
chrono = "0.4.45"
serde = "1.0.229"
backon = "1.6.0"
serde_json = "1.0.151"
sea-orm = { version = "1.1.20", features = ["sqlx-sqlite", "sqlx-postgres", "runtime-tokio-rustls", "macros", "with-bigdecimal"] }
itertools = "0.15.0"
flate2 = "1.1.9"
tar = "0.4.46"
utoipa = { version = "5.5.0", features = ["rocket_extras"] }
tempfile = "3.27.0"
alpm-srcinfo = "0.6.3"

[profile.release]
strip = "debuginfo"  # Automatically strip symbols from the binary.
opt-level = "z"  # Optimize for size.
lto = true  # Enable link-time optimization.
codegen-units = 1
