//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.2

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use std::fmt::Display;
use std::str::FromStr;
use utoipa::ToSchema;

#[derive(Clone, Debug, Default, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct GitSourceSpec {
    pub url: String,
    pub r#ref: String,
    pub subfolder: String,
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize, ToSchema, DeriveValueType)]
#[sea_orm(value_type = "String")]
#[serde(tag = "type")]
pub enum SourceData {
    #[serde(rename = "aur")]
    Aur { name: String },
    #[serde(rename = "git")]
    Git {
        #[serde(flatten)]
        spec: GitSourceSpec,
    },
    #[serde(rename = "upload")]
    Upload { archive: Vec<u8> },
}

impl From<GitSourceSpec> for SourceData {
    fn from(spec: GitSourceSpec) -> Self {
        Self::Git { spec }
    }
}

impl FromStr for SourceData {
    type Err = anyhow::Error;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        let value: Self = serde_json::from_str(s)?;
        Ok(value)
    }
}

impl SourceData {
    /// Unique cache key for this source.
    pub fn cache_key(&self) -> String {
        match self {
            SourceData::Aur { name } => format!("aur:{name}"),
            SourceData::Git { spec } => {
                format!("git:{}:{}:{}", spec.url, spec.r#ref, spec.subfolder)
            }
            SourceData::Upload { .. } => "upload".to_string(),
        }
    }
}

impl Display for SourceData {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(
            f,
            "{}",
            serde_json::to_string(self).map_err(|_| std::fmt::Error)?
        )
    }
}

// todo the toSchema derive should be removed to couple db and api
#[derive(
    Clone, Debug, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize, ToSchema,
)]
#[sea_orm(rs_type = "String", db_type = "Text")]
#[derive(Default)]
pub enum SourceType {
    #[sea_orm(string_value = "aur")]
    #[default]
    Aur,
    #[sea_orm(string_value = "git")]
    Git,
    #[sea_orm(string_value = "upload")]
    Upload,
}

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, ToSchema)]
#[sea_orm(table_name = "packages")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    /// Canonical package identifier (this is the pkgbase).
    ///
    /// We track one row per pkgbase, so `name` stores the pkgbase value.
    pub name: String,
    pub status: i32,
    pub out_of_date: i32,
    pub upstream_version: Option<String>,
    pub latest_build: Option<i32>,
    pub build_flags: String,
    pub platforms: String,
    pub source_type: SourceType,
    #[schema(value_type = String)]
    pub source_data: SourceData,
    pub directly_requested: bool,
    pub split_packages: Option<String>,
    pub provides: Option<String>,
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::builds::Entity")]
    Builds,
    #[sea_orm(has_many = "super::files::Entity")]
    Files,
    #[sea_orm(
        belongs_to = "super::builds::Entity",
        from = "Column::LatestBuild",
        to = "super::builds::Column::Id"
    )]
    LatestBuild,
}

impl Related<super::files::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Files.def()
    }
}

impl Related<super::builds::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Builds.def()
    }
}
