name: Build and Push Docker Image

on:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  build-and-push-arm64:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version tag
        id: extract_tag
        run: echo "::set-output name=tag::${GITHUB_REF#refs/tags/}"

      - id: repo_name_lc
        uses: ASzc/change-string-case-action@v6
        with:
         string: ${{ github.repository }}

      - name: Build and push Docker image for main branch
        if: github.ref == 'refs/heads/master'
        run: |
          docker build --build-arg TARGET_ARCH=linux/amd64 -f ./docker/Dockerfile -t ghcr.io/${{ steps.repo_name_lc.outputs.lowercase }}:git .
          docker push ghcr.io/${{ steps.repo_name_lc.outputs.lowercase }}:git

      - name: Build and push Docker image for tag
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          docker build --build-arg TARGET_ARCH=linux/amd64 -f ./docker/Dockerfile -t ghcr.io/${{ steps.repo_name_lc.outputs.lowercase }}:${{ steps.extract_tag.outputs.tag }} .
          docker tag ghcr.io/${{ steps.repo_name_lc.outputs.lowercase }}:${{ steps.extract_tag.outputs.tag }} ghcr.io/${{ steps.repo_name_lc.outputs.lowercase }}:latest
          docker push ghcr.io/${{ steps.repo_name_lc.outputs.lowercase }}:${{ steps.extract_tag.outputs.tag }}
          docker push ghcr.io/${{ steps.repo_name_lc.outputs.lowercase }}:latest

  build-and-push-aarch64:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version tag
        id: extract_tag
        run: echo "::set-output name=tag::${GITHUB_REF#refs/tags/}"

      - id: repo_name_lc
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{ github.repository }}

      - name: Build and push ARM64 Docker image for main branch
        if: github.ref == 'refs/heads/master'
        run: |
          docker build --build-arg TARGET_ARCH=linux/arm64/v8 -f ./docker/Dockerfile.arm64 -t ghcr.io/${{ steps.repo_name_lc.outputs.lowercase }}:git .
          docker push ghcr.io/${{ steps.repo_name_lc.outputs.lowercase }}:git

      - name: Build and push ARM64 Docker image for tag
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          docker build --build-arg TARGET_ARCH=linux/arm64/v8 -f ./docker/Dockerfile.arm64 -t ghcr.io/${{ steps.repo_name_lc.outputs.lowercase }}:${{ steps.extract_tag.outputs.tag }} .
          docker tag ghcr.io/${{ steps.repo_name_lc.outputs.lowercase }}:${{ steps.extract_tag.outputs.tag }} ghcr.io/${{ steps.repo_name_lc.outputs.lowercase }}:latest
          docker push ghcr.io/${{ steps.repo_name_lc.outputs.lowercase }}:${{ steps.extract_tag.outputs.tag }}
          docker push ghcr.io/${{ steps.repo_name_lc.outputs.lowercase }}:latest