name: Docker Build/Publish Image

on:
  push:
    branches:
      - '**'
      - '!master'

jobs:
  build:    
    runs-on: ubuntu-latest
    env:
      DOCKER_TARGET_PLATFORM: linux/arm64/v8

    steps:
    - name: Checkout the code       
      uses: actions/checkout@v1
    - name: Set up Docker Buildx
      uses: crazy-max/ghaction-docker-buildx@v1      
      with:        
        version: latest
    - name: Prepare
      id: prepare
      run: |        
        echo ::set-output name=docker_platform::${DOCKER_TARGET_PLATFORM}
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Run Buildx (push image)
      run: |
        docker buildx build \
        --platform ${{ steps.prepare.outputs.docker_platform }} \
        --file ./Dockerfile \
        --output type=image,push=false .