name: Make helper containers
on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * 1"   # <=== Change this value

jobs:
  build:
    name: Build AUR enabled Arch containers
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - id: repo_name_lc
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{ github.repository }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build paru container
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          context: .
          file: ./docker/builder.Dockerfile
          tags: |
            ghcr.io/lukas-heiligenbrunner/aurcache-builder:latest